name: Deploy Hexo to GitHub Pages

# 触发事件：每次 push 到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出源代码
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # 步骤 2：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 根据你的项目需求选择 Node.js 版本

      # 步骤 3：安装依赖
      - name: Install Dependencies
        run: |
          npm install

      # 步骤 4：生成静态文件
      - name: Generate Hexo Site
        run: |
          npx hexo clean
          npx hexo generate

      # 步骤 5：推送静态文件到目标仓库的 docs 文件夹
      - name: Deploy to GitHub Pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: TabNahida/TabNahida.github.io  # 目标仓库
          branch: main  # 目标仓库的分支（通常是 main）
          folder: public  # Hexo 默认生成静态文件的文件夹
          target-folder: docs  # 目标仓库中的目标文件夹
          github_token: ${{ secrets.TARGET_REPO_TOKEN }}